import { UserContext, UserProvider } from "./context/userContext";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Asistencia RFID",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <UserProvider>
      <html lang="en" className='dark'>
        <body className={inter.className}>{children}</body>
      </html>
    </UserProvider>
  );
}
